Update BOSC_review_process.md
OBF/bosc_materials pull request #28
Opened 2022-10-09 08:32 UTC by deepakunni3

- Add link to Review of Reviews SOP document

2022-10-09 19:06 UTC, nlharris commented on BOSC_review_process.md
> +After reviewers have submitted their reviews, a sub-committee will evaluate all reviews to make sure they are appropriate, and to ensure all reviewer comments are in line with the conference Code of
```suggestion
After reviewers have submitted their reviews, a sub-committee will evaluate all reviews to make sure they are appropriate, and to ensure all reviewer comments are in line with the conference Code of Conduct. Refer to the [Review of Reviews SOP](https://docs.google.com/document/d/1HFbHD2K4CORRqHsqh5_yLea47XcujSSLUkydnSYsMnY/edit) to learn more about the process and how the subcommittee is organized. If a decision is made that part or all of a review is non-compliant, we will ensure that the offending text is not included as part of the scoring process and is edited by the sub-committee before passing along any useful comments to the authors. Such decisions will be made on a case-by-case basis.
```

2022-10-09 19:09 UTC, nlharris requested changes

2022-10-09 19:09 UTC, nlharris commented on BOSC_review_process.md
> +After reviewers have submitted their reviews, a sub-committee will evaluate all reviews to make sure they are appropriate, and to ensure all reviewer comments are in line with the conference Code of
Thanks! Please add date (May 2022) to RoR doc.

2022-10-09 19:09 UTC, nlharris commented on BOSC_review_process.md
> +(Note that the [OBF Code of Conduct](https://github.com/OBF/obf-docs/pull/78) is currently in development; for BOSC 2022, the [ISMB/ECCB Code of Conduct](https://www.iscb.org/iscb-policy-statements/i
The OBF Code of Conduct was approved and merged in Jan 2022: https://github.com/OBF/obf-docs/tree/master/code-of-conduct

Need clarification here on which CoC applies to the RoR -- OBF or ISMB. (I'm actually not sure which it should be!)

2022-10-11 06:55 UTC, deepakunni3 commented on BOSC_review_process.md
> +After reviewers have submitted their reviews, a sub-committee will evaluate all reviews to make sure they are appropriate, and to ensure all reviewer comments are in line with the conference Code of
done!

2022-10-11 06:57 UTC, deepakunni3 commented on BOSC_review_process.md
> +(Note that the [OBF Code of Conduct](https://github.com/OBF/obf-docs/pull/78) is currently in development; for BOSC 2022, the [ISMB/ECCB Code of Conduct](https://www.iscb.org/iscb-policy-statements/i
Yes, not clear either. Wouldn't ISMB COC apply only if BOSC is co-located with ISMB? Then it would differ on a year-by-year basis, right?

2022-10-11 10:03 UTC, peterjc commented on BOSC_review_process.md
> +(Note that the [OBF Code of Conduct](https://github.com/OBF/obf-docs/pull/78) is currently in development; for BOSC 2022, the [ISMB/ECCB Code of Conduct](https://www.iscb.org/iscb-policy-statements/i
Also https://github.com/OBF/obf-docs/pull/78 has been merged now, so the OBF CoC is no longer "in development".

2022-10-11 10:05 UTC, peterjc commented
Is the "Review of Reviews SOP" sufficiently stable that it could be hosted here as another markdown file (rather than an external Google Document)?

2022-10-11 20:54 UTC, nlharris commented
> Is the "Review of Reviews SOP" sufficiently stable that it could be hosted here as another markdown file (rather than an external Google Document)?

Other than dates and names, probably; we were trying to lower the bar to get it linked without requiring a lot of extra work to convert it to markdown, which would also entail removing the variable bits or requiring future PRs to change them.

2022-10-11 20:55 UTC, nlharris commented on BOSC_review_process.md
> +(Note that the [OBF Code of Conduct](https://github.com/OBF/obf-docs/pull/78) is currently in development; for BOSC 2022, the [ISMB/ECCB Code of Conduct](https://www.iscb.org/iscb-policy-statements/i
Right, I said just above that the OBF CoC was approved and merged. But which CoC applies here?

2022-12-02 22:23 UTC, nlharris approved these changes

2022-12-02 22:23 UTC, merged